Add `name: ""` to CSV resources list
Add the `name: ""` parameter to the CSV `resources` list so that it passes validation.

Without this change when importing to a modern Kubernetes, you get this error:

```
error: error validating "STDIN": error validating data: [ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[0]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[1]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[2]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[3]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[4]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[5]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[6]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[7]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[8]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources, ValidationError(ClusterServiceVersion.spec.customresourcedefinitions.owned[0].resources[9]): missing required field "name" in com.coreos.operators.v1alpha1.ClusterServiceVersion.spec.customresourcedefinitions.owned.resources]; if you choose to ignore these errors, turn validation off with --validate=false
```